/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package opencv;

import static com.googlecode.javacv.cpp.opencv_core.cvScalar;

/**
 *
 * @author Toky
 */
public class Controleur extends javax.swing.JFrame {

    /**
     * Creates new form Controleur
     */
    public Controleur() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        hmax = new javax.swing.JSlider();
        hmin = new javax.swing.JSlider();
        smax = new javax.swing.JSlider();
        smin = new javax.swing.JSlider();
        vmax = new javax.swing.JSlider();
        vmin = new javax.swing.JSlider();
        zone_hmax = new javax.swing.JTextField();
        zone_hmin = new javax.swing.JTextField();
        zone_smax = new javax.swing.JTextField();
        zone_smin = new javax.swing.JTextField();
        zone_vmax = new javax.swing.JTextField();
        zone_vmin = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.GridBagLayout());

        hmax.setMaximum(180);
        hmax.setValue(20);
        hmax.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                hmaxStateChanged(evt);
            }
        });
        hmax.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                hmaxPropertyChange(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 256;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 4, 0, 0);
        jPanel1.add(hmax, gridBagConstraints);

        hmin.setMaximum(180);
        hmin.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                hminStateChanged(evt);
            }
        });
        hmin.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                hminPropertyChange(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 256;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 4, 0, 0);
        jPanel1.add(hmin, gridBagConstraints);

        smax.setMaximum(255);
        smax.setValue(60);
        smax.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                smaxStateChanged(evt);
            }
        });
        smax.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                smaxPropertyChange(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 256;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 4, 0, 0);
        jPanel1.add(smax, gridBagConstraints);

        smin.setMaximum(255);
        smin.setValue(200);
        smin.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sminStateChanged(evt);
            }
        });
        smin.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                sminPropertyChange(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 256;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 4, 0, 0);
        jPanel1.add(smin, gridBagConstraints);

        vmax.setMaximum(255);
        vmax.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                vmaxStateChanged(evt);
            }
        });
        vmax.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                vmaxPropertyChange(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 256;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 4, 0, 0);
        jPanel1.add(vmax, gridBagConstraints);

        vmin.setMaximum(255);
        vmin.setValue(255);
        vmin.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                vminStateChanged(evt);
            }
        });
        vmin.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                vminPropertyChange(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.ipadx = 256;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 4, 11, 0);
        jPanel1.add(vmin, gridBagConstraints);

        zone_hmax.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                zone_hmaxKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 53;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 6, 0, 17);
        jPanel1.add(zone_hmax, gridBagConstraints);

        zone_hmin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                zone_hminKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 53;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 0, 17);
        jPanel1.add(zone_hmin, gridBagConstraints);

        zone_smax.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                zone_smaxKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 53;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 0, 17);
        jPanel1.add(zone_smax, gridBagConstraints);

        zone_smin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                zone_sminKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.ipadx = 53;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 0, 17);
        jPanel1.add(zone_smin, gridBagConstraints);

        zone_vmax.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                zone_vmaxKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.ipadx = 53;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 0, 17);
        jPanel1.add(zone_vmax, gridBagConstraints);

        zone_vmin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                zone_vminKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.ipadx = 53;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 6, 11, 17);
        jPanel1.add(zone_vmin, gridBagConstraints);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Hmax");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 11;
        gridBagConstraints.ipady = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 10, 0, 0);
        jPanel1.add(jLabel1, gridBagConstraints);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Hmin");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 14;
        gridBagConstraints.ipady = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 10, 0, 0);
        jPanel1.add(jLabel2, gridBagConstraints);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Smax");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 12;
        gridBagConstraints.ipady = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 10, 0, 0);
        jPanel1.add(jLabel3, gridBagConstraints);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Smin");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 15;
        gridBagConstraints.ipady = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 10, 0, 0);
        jPanel1.add(jLabel4, gridBagConstraints);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Vmax");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 12;
        gridBagConstraints.ipady = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 10, 0, 0);
        jPanel1.add(jLabel5, gridBagConstraints);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Vmin");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.ipadx = 15;
        gridBagConstraints.ipady = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 10, 11, 0);
        jPanel1.add(jLabel6, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void hmaxPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_hmaxPropertyChange

    }//GEN-LAST:event_hmaxPropertyChange

    private void hminPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_hminPropertyChange
        TesteJavaCV6A.Bminc = cvScalar(hmax.getValue(), smax.getValue(), vmax.getValue(), 0);
        TesteJavaCV6A.Bmaxc = cvScalar(hmin.getValue(), smin.getValue(), vmin.getValue(), 0);
        TesteJavaCV6A.Rminc = cvScalar(hmax.getValue(), smax.getValue(), vmax.getValue(), 0);
        TesteJavaCV6A.Rmaxc = cvScalar(hmin.getValue(), smin.getValue(), vmin.getValue(), 0);
        zone_hmax.setText(hmin.getValue() + "");
    }//GEN-LAST:event_hminPropertyChange

    private void smaxPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_smaxPropertyChange

    }//GEN-LAST:event_smaxPropertyChange

    private void sminPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_sminPropertyChange

    }//GEN-LAST:event_sminPropertyChange

    private void vmaxPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_vmaxPropertyChange
        TesteJavaCV6A.Bminc = cvScalar(hmax.getValue(), smax.getValue(), vmax.getValue(), 0);
        TesteJavaCV6A.Bmaxc = cvScalar(hmin.getValue(), smin.getValue(), vmin.getValue(), 0);
        TesteJavaCV6A.Rminc = cvScalar(hmax.getValue(), smax.getValue(), vmax.getValue(), 0);
        TesteJavaCV6A.Rmaxc = cvScalar(hmin.getValue(), smin.getValue(), vmin.getValue(), 0);
        zone_vmin.setText(vmax.getValue() + "");
    }//GEN-LAST:event_vmaxPropertyChange

    private void vminPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_vminPropertyChange

    }//GEN-LAST:event_vminPropertyChange

    private void hmaxStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_hmaxStateChanged
        TesteJavaCV6A.Bminc = cvScalar(hmax.getValue(), smax.getValue(), vmax.getValue(), 0);
        TesteJavaCV6A.Bmaxc = cvScalar(hmin.getValue(), smin.getValue(), vmin.getValue(), 0);
        TesteJavaCV6A.Rminc = cvScalar(hmax.getValue(), smax.getValue(), vmax.getValue(), 0);
        TesteJavaCV6A.Rmaxc = cvScalar(hmin.getValue(), smin.getValue(), vmin.getValue(), 0);
        zone_hmax.setText(hmax.getValue() + "");
    }//GEN-LAST:event_hmaxStateChanged

    private void hminStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_hminStateChanged
        TesteJavaCV6A.Bminc = cvScalar(hmax.getValue(), smax.getValue(), vmax.getValue(), 0);
        TesteJavaCV6A.Bmaxc = cvScalar(hmin.getValue(), smin.getValue(), vmin.getValue(), 0);
        TesteJavaCV6A.Rminc = cvScalar(hmax.getValue(), smax.getValue(), vmax.getValue(), 0);
        TesteJavaCV6A.Rmaxc = cvScalar(hmin.getValue(), smin.getValue(), vmin.getValue(), 0);
        zone_hmin.setText(hmin.getValue() + "");
    }//GEN-LAST:event_hminStateChanged

    private void smaxStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_smaxStateChanged
        TesteJavaCV6A.Bminc = cvScalar(hmax.getValue(), smax.getValue(), vmax.getValue(), 0);
        TesteJavaCV6A.Bmaxc = cvScalar(hmin.getValue(), smin.getValue(), vmin.getValue(), 0);
        TesteJavaCV6A.Rminc = cvScalar(hmax.getValue(), smax.getValue(), vmax.getValue(), 0);
        TesteJavaCV6A.Rmaxc = cvScalar(hmin.getValue(), smin.getValue(), vmin.getValue(), 0);
        zone_smax.setText(smax.getValue() + "");
    }//GEN-LAST:event_smaxStateChanged

    private void sminStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sminStateChanged
        TesteJavaCV6A.Bminc = cvScalar(hmax.getValue(), smax.getValue(), vmax.getValue(), 0);
        TesteJavaCV6A.Bmaxc = cvScalar(hmin.getValue(), smin.getValue(), vmin.getValue(), 0);
        TesteJavaCV6A.Rminc = cvScalar(hmax.getValue(), smax.getValue(), vmax.getValue(), 0);
        TesteJavaCV6A.Rmaxc = cvScalar(hmin.getValue(), smin.getValue(), vmin.getValue(), 0);
        zone_smin.setText(smin.getValue() + "");
    }//GEN-LAST:event_sminStateChanged

    private void vmaxStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_vmaxStateChanged
        TesteJavaCV6A.Bminc = cvScalar(hmax.getValue(), smax.getValue(), vmax.getValue(), 0);
        TesteJavaCV6A.Bmaxc = cvScalar(hmin.getValue(), smin.getValue(), vmin.getValue(), 0);
        TesteJavaCV6A.Rminc = cvScalar(hmax.getValue(), smax.getValue(), vmax.getValue(), 0);
        TesteJavaCV6A.Rmaxc = cvScalar(hmin.getValue(), smin.getValue(), vmin.getValue(), 0);
        zone_vmax.setText(vmax.getValue() + "");
    }//GEN-LAST:event_vmaxStateChanged

    private void vminStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_vminStateChanged
        TesteJavaCV6A.Bminc = cvScalar(hmax.getValue(), smax.getValue(), vmax.getValue(), 0);
        TesteJavaCV6A.Bmaxc = cvScalar(hmin.getValue(), smin.getValue(), vmin.getValue(), 0);
        TesteJavaCV6A.Rminc = cvScalar(hmax.getValue(), smax.getValue(), vmax.getValue(), 0);
        TesteJavaCV6A.Rmaxc = cvScalar(hmin.getValue(), smin.getValue(), vmin.getValue(), 0);
        zone_vmin.setText(vmin.getValue() + "");
    }//GEN-LAST:event_vminStateChanged

    private void zone_hmaxKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_zone_hmaxKeyReleased
        hmax.setValue(Integer.parseInt(zone_hmin.getText()));
    }//GEN-LAST:event_zone_hmaxKeyReleased

    private void zone_hminKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_zone_hminKeyReleased
        hmin.setValue(Integer.parseInt(zone_hmax.getText()));
    }//GEN-LAST:event_zone_hminKeyReleased

    private void zone_smaxKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_zone_smaxKeyReleased
        vmax.setValue(Integer.parseInt(zone_vmin.getText()));
    }//GEN-LAST:event_zone_smaxKeyReleased

    private void zone_sminKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_zone_sminKeyReleased
        vmin.setValue(Integer.parseInt(zone_vmax.getText()));
    }//GEN-LAST:event_zone_sminKeyReleased

    private void zone_vmaxKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_zone_vmaxKeyReleased
        smin.setValue(Integer.parseInt(zone_smax.getText()));
    }//GEN-LAST:event_zone_vmaxKeyReleased

    private void zone_vminKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_zone_vminKeyReleased
        smax.setValue(Integer.parseInt(zone_smin.getText()));
    }//GEN-LAST:event_zone_vminKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Controleur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Controleur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Controleur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Controleur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Controleur().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JSlider hmax;
    public static javax.swing.JSlider hmin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JSlider smax;
    public static javax.swing.JSlider smin;
    public static javax.swing.JSlider vmax;
    public static javax.swing.JSlider vmin;
    private javax.swing.JTextField zone_hmax;
    private javax.swing.JTextField zone_hmin;
    private javax.swing.JTextField zone_smax;
    private javax.swing.JTextField zone_smin;
    private javax.swing.JTextField zone_vmax;
    private javax.swing.JTextField zone_vmin;
    // End of variables declaration//GEN-END:variables
}
